= igdb
:doctype: article
:sectnums:
:toc:

Modul 227

== Klassendiagramm
[plantuml]
-----
@startuml
Class Game{
+id
+Name
+ReleaseDate
+Publisher
+GameDirector
+Downloads
+price
+Crossplay
+platfrom
+Category
+Size
}
Enum category{
+Category
}
class Publisher{
+id
+name
+Employees
+MarketCap
+CEO
}
class Platform{
+id
+Name
+players
}
Game -- category
Game "m" -- "m" Platform
Game "m" -- "1" Publisher
@enduml
-----




== Usecases

.Usecasediagramm von IGDB
[plantuml]
----
class b
----

=== UC-1 Developer
Ich will den Developer von einem Spiel anzeigen lassen.

Ich will alle Games von einem Developer sehen.

==== Sequenz

=== UC-2 Platformen
Ich will von jedem Game die verfügbaren Platformen sehen.

Ich will von jeder Platform alle Games sehen.

==== Sequenz

=== Game

Ich will von jedem Game die Spieleranzahl sehen.

Ich will von jedem Game die Bewertung sehen.

==== Sequenz

== Test Case

path: /
Auf dem Main window ist es so Das wen man auf das I bei einer Katrte drückt sollte Die Tabelle mit den Spezifikation des Objekts Auf kommen. Einfach alle Atribute
Der Knopf Sign in wird dich auf das crud weiter leiten
Path: /crud
Beim crud werden alle Tablen angezeigt die man bearbeiten kann

Mit Funktionen und so